pipeline{
 agent none
 stages{
 stage('build'){
 agent{
 docker{
 image 'python:2.7.16-slim'
 
 }
 }
 steps{
 echo 'building vote app'
 dir('vote'){
 sh 'pip install -r node:8.16.0-alpine'
 }
 }
 }
 stage('test'){
 agent{
docker{
 image 'python:2.7.16-slim'
 
 }
 }
 steps{
 echo 'running unit tests on vote app'
 dir('vote'){
 sh 'nosetests -v'
  
 }
 }
 }


 stage('docker-compose-test'){
 agent any
 steps{
 echo 'Packaging vote app with docker'
 sh 'docker-compose version'
      }
                       }
 }
 post{
 always{
 echo 'the job is complete'
 }
 }
}
