pipeline{
 agent none
 stages{
 stage('build'){
 agent{
 docker{
 image 'python:2.7.16-slim'
 
 }
 }
 steps{
 echo 'building vote app'
 dir('vote'){
 sh 'pip install -r requirements.txt'
 }
 }
 }
 stage('test'){
 agent{
docker{
 image 'python:2.7.16-slim'
 
 }
 }
 steps{
 echo 'running unit tests on vote app'
 dir('vote'){
 sh 'nosetests -v'
  
 }
 }
 }


// stage('docker-package'){
// agent any
// steps{
// echo 'Packaging vote app with docker'
// script{
// docker.withRegistry('https://index.docker.io/v1/','dockerlogin') {
// def voteImage = docker.build("hamdymoussa/vote:v${env.BUILD_ID}", "./vote")
// voteImage.push()
// voteImage.push("${env.BRANCH_NAME}") 
// voteImage.push("latest")
                                                                  }
//       }
//      }
//                       }
 stage('docker-compose-test'){
 agent any
 steps{
 echo 'Packaging vote app with docker'
 sh 'docker-compose version'
      }
                       }
 }
 post{
 always{
 echo 'the job is complete'
 }
 }
}
